### ISSUE TITLE
ng 스타일가이드 john papa 거 번역

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Notes#3]
하라고 막 @haruair 찡이 갈굼. ㄷㄷㄷ

쪼끔 하긴 했음. ㄷㄷㄷ

[https://github.com/justinyoo/angular-styleguide/blob/dev/i18n/ko-KR.md](https://github.com/justinyoo/angular-styleguide/blob/dev/i18n/ko-KR.md)

**Comment by haruair** [comment]
엯촋 :+1:
